//
// Created by fabian on 19.09.26.
//

#ifndef FUN_USING_COMPUTATIONAL_CHEMISTRY_DIAGMAT_HPP
#define FUN_USING_COMPUTATIONAL_CHEMISTRY_DIAGMAT_HPP

#endif //FUN_USING_COMPUTATIONAL_CHEMISTRY_DIAGMAT_HPP
